### ISSUE TITLE
segfault on linux

### ISSUE THREAD

**Issue by pastascript** [Neo23x0/log4shell-detector#14]
Script exits with a segfault on CentOS 7/8

```
go run log4j-vuln-finder.go /
/tmp/go-build257162864/b001/exe/log4j-vuln-finder - a simple local log4j vulnerability scanner

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4c8075]

goroutine 1 [running]:
main.main.func1(0xc0001cb6a0, 0x11, 0x0, 0x0, 0x5195c0, 0xc000202030, 0x0, 0x0)
        /home/<USER>/local-log4j-vuln-scanner/log4j-vuln-finder.go:120 +0x55
path/filepath.walk(0xc000480f10, 0xf, 0x51a320, 0xc0001fd930, 0x4fe030, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:380 +0x213
path/filepath.walk(0xc000480ce0, 0xc, 0x51a320, 0xc0001fc9c0, 0x4fe030, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc00013ff16, 0x5, 0x51a320, 0xc00030c8f0, 0x4fe030, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0x7ffdfd65d66e, 0x1, 0x51a320, 0xc00005cdd0, 0x4fe030, 0x0, 0x60)
        /usr/lib/golang/src/path/filepath/path.go:384 +0x2fe
path/filepath.Walk(0x7ffdfd65d66e, 0x1, 0x4fe030, 0x31, 0xc000062f68)
        /usr/lib/golang/src/path/filepath/path.go:406 +0x105
main.main()
        /home/<USER>/local-log4j-vuln-scanner/log4j-vuln-finder.go:119 +0x208
exit status 2
```

**Comment by pastascript** [comment]
nevermind... this was for a different project, too many open tabs
